### ISSUE TITLE
Training to Complete

### ISSUE THREAD

**Issue by poonamsaini17** [watson-developer-cloud/professor-languo#5] opened 2016-05-04 17:34 UTC
Hi , 
I am trying with this app which you have developed but i am facing issue while creating training data ..

```
2016-05-03 12:45:15,167 INFO  [main] pipeline.PipelineDriver (PipelineDriver.java:93) - Training set has 22 questions and 22 answers
2016-05-03 12:45:15,168 INFO  [main] pipeline.PipelineDriver (PipelineDriver.java:99) - Validation set has 0 questions and 0 answers
2016-05-03 12:45:15,169 INFO  [main] pipeline.PipelineDriver (PipelineDriver.java:105) - Test set has 0 questions and 0 answers
2016-05-03 12:45:15,204 INFO  [main] api.PipelineQuestionAnswerer (PipelineQuestionAnswerer.java:288) - Initializing scheduler with 1 threads.
2016-05-03 12:45:15,634 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:116) - Solr cluster - sca202f2a2_ecb7_43ca_9e6e_aa981e812496
2016-05-03 12:45:15,634 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:117) - Solr collection - collection_name
2016-05-03 12:45:15,634 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:118) - Ranker name - ranker_name
2016-05-03 12:45:15,634 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:119) - Rows per query - 50
2016-05-03 12:45:15,636 INFO  [main] api.PipelineQuestionAnswerer (PipelineQuestionAnswerer.java:135) - number of folds:1
2016-05-03 12:45:15,636 INFO  [main] api.PipelineQuestionAnswerer (PipelineQuestionAnswerer.java:136) - trainable components:[]
2016-05-03 12:45:15,674 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 4323
2016-05-03 12:45:21,699 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 4386
2016-05-03 12:45:29,242 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 4513
2016-05-03 12:45:32,330 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 237
2016-05-03 12:45:34,228 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 346
2016-05-03 12:45:36,391 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 380
2016-05-03 12:45:38,246 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 625
2016-05-03 12:45:39,828 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 4643
2016-05-03 12:45:41,383 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 831
2016-05-03 12:45:43,223 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 938
2016-05-03 12:45:45,257 INFO  [pool-3-thread-1] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:252) - So far, 10 out of 9 questions have been retained
2016-05-03 12:45:45,258 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 4817
2016-05-03 12:45:47,361 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 1195
2016-05-03 12:45:49,823 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 1261
2016-05-03 12:45:53,836 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 1456
2016-05-03 12:45:59,145 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 1627
2016-05-03 12:46:01,438 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 1922
2016-05-03 12:46:02,962 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 3101
2016-05-03 12:46:04,464 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 3511
2016-05-03 12:46:05,995 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 3548
2016-05-03 12:46:08,876 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 3403
2016-05-03 12:46:11,657 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 3417
2016-05-03 12:46:14,256 INFO  [pool-3-thread-1] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:252) - So far, 20 out of 20 questions have been retained
2016-05-03 12:46:14,257 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 3947
2016-05-03 12:46:17,763 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:160) - Attempting to create ranker.
2016-05-03 12:46:24,167 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:163) - Writing training data to disk
2016-05-03 12:46:24,183 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:167) - Writing training data to disk done
2016-05-03 12:46:26,359 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:176) - Kicking off training on data file:res/training_data.csv
2016-05-03 12:46:26,359 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:180) - Ranker status : Training
2016-05-03 12:46:58,663 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:180) - Ranker status : Training
2016-05-03 12:47:30,858 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:180) - Ranker status : Training
2016-05-03 12:48:03,213 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:180) - Ranker status : Training
2016-05-03 12:48:35,349 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:180) - Ranker status : Training
Exception in thread "main" java.lang.RuntimeException: Ranker training failed.
    at com.ibm.watson.developer_cloud.professor_languo.pipeline.RnrMergerAndRanker.finishTraining(RnrMergerAndRanker.java:188)
    at com.ibm.watson.developer_cloud.professor_languo.api.PipelineQuestionAnswerer.train(PipelineQuestionAnswerer.java:164)
    at com.ibm.watson.developer_cloud.professor_languo.api.PipelineQuestionAnswerer.trainWithComponentTrainingData(PipelineQuestionAnswerer.java:126)
    at com.ibm.watson.developer_cloud.professor_languo.api.PipelineQuestionAnswerer.train(PipelineQuestionAnswerer.java:96)
    at com.ibm.watson.developer_cloud.professor_languo.pipeline.PipelineDriver.drive(PipelineDriver.java:115)
    at com.ibm.watson.developer_cloud.professor_languo.pipeline.PipelineDriver.main(PipelineDriver.java:59)
```

**Comment by stevenoh93** [comment] 2016-05-04 18:26
Hello,

One of the requirements of the training data is that [The file must contain at least 49 unique questions.](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/retrieve-rank/training_data.shtml)
Could you try to get more training data? Or use a corpus from [StackExchange](http://data.stackexchange.com/)?

**Comment by germanattanasio** [comment] 2016-05-04 19:00
@dbanda do you have an idea of what this is ?

**Comment by dbanda** [comment] 2016-05-04 20:27
I agree with Steven. It looks like there is something wrong with your training data. Check that is complies with the requirements.

**Comment by poonamsaini17** [comment] 2016-05-05 02:36
I used a corpus of health stack .
While indexing it showed almost 50 answers...

**Comment by poonamsaini17** [comment] 2016-05-05 07:37
I tried again , can you tell me now where i am doing the mistake? 
1)
[output_ingestion.txt](https://github.com/watson-developer-cloud/professor-languo/files/250065/output_ingestion.txt)

2)

``` none
2016-05-05 12:59:46,412 INFO  [main] pipeline.PipelineDriver (PipelineDriver.java:93) - Training set has 54 questions and 54 answers
2016-05-05 12:59:46,412 INFO  [main] pipeline.PipelineDriver (PipelineDriver.java:99) - Validation set has 0 questions and 0 answers
2016-05-05 12:59:46,412 INFO  [main] pipeline.PipelineDriver (PipelineDriver.java:105) - Test set has 0 questions and 0 answers
2016-05-05 12:59:46,793 INFO  [main] api.PipelineQuestionAnswerer (PipelineQuestionAnswerer.java:288) - Initializing scheduler with 1 threads.
2016-05-05 12:59:47,303 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:116) - Solr cluster - sc75089e73_2a3b_4e9f_ae1e_4c7cfa09878d
2016-05-05 12:59:47,303 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:117) - Solr collection - collection_name
2016-05-05 12:59:47,303 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:118) - Ranker name - ranker_name
2016-05-05 12:59:47,303 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:119) - Rows per query - 50
2016-05-05 12:59:47,353 INFO  [main] api.PipelineQuestionAnswerer (PipelineQuestionAnswerer.java:135) - number of folds:1
2016-05-05 12:59:47,353 INFO  [main] api.PipelineQuestionAnswerer (PipelineQuestionAnswerer.java:136) - trainable components:[]
2016-05-05 12:59:47,423 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 8794
2016-05-05 12:59:53,524 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 8914
2016-05-05 12:59:57,498 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 8894
2016-05-05 13:00:02,387 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 9015
2016-05-05 13:00:06,019 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 9123
2016-05-05 13:00:07,762 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 8185
2016-05-05 13:00:09,243 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 8390
2016-05-05 13:00:10,504 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 8414
2016-05-05 13:00:11,755 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 8647
2016-05-05 13:00:12,706 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 8588
2016-05-05 13:00:13,677 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 9858
2016-05-05 13:00:14,641 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 9229
2016-05-05 13:00:15,591 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 9317
2016-05-05 13:00:16,302 INFO  [pool-3-thread-1] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:252) - So far, 10 out of 12 questions have been retained
2016-05-05 13:00:16,302 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 9362
2016-05-05 13:00:17,524 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 9375
2016-05-05 13:00:18,237 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 9433
2016-05-05 13:00:18,937 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 9445
2016-05-05 13:00:19,612 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 9499
2016-05-05 13:00:20,350 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 9561
2016-05-05 13:00:21,126 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 11147
2016-05-05 13:00:21,806 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 2508
2016-05-05 13:00:22,533 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 2521
2016-05-05 13:00:23,723 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 2316
2016-05-05 13:00:24,926 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 2660
2016-05-05 13:00:25,873 INFO  [pool-3-thread-1] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:252) - So far, 20 out of 23 questions have been retained
2016-05-05 13:00:25,873 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 3966
2016-05-05 13:00:26,846 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 13122
2016-05-05 13:00:28,135 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 13055
2016-05-05 13:00:29,356 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 13070
2016-05-05 13:00:30,300 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 13179
2016-05-05 13:00:31,340 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 12790
2016-05-05 13:00:32,592 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 12620
2016-05-05 13:00:35,569 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 12563
2016-05-05 13:00:39,409 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 4975
2016-05-05 13:00:43,446 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 12748
2016-05-05 13:00:45,968 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 12679
2016-05-05 13:00:47,946 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 12264
2016-05-05 13:00:49,643 INFO  [pool-3-thread-1] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:252) - So far, 30 out of 35 questions have been retained
2016-05-05 13:00:49,643 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 12288
2016-05-05 13:00:51,105 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 13797
2016-05-05 13:00:52,056 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 5287
2016-05-05 13:00:53,263 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 13556
2016-05-05 13:00:53,944 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 13688
2016-05-05 13:00:54,856 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 13759
2016-05-05 13:00:55,647 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 13281
2016-05-05 13:00:56,358 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 13311
2016-05-05 13:00:57,048 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 5613
2016-05-05 13:00:57,729 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 13371
2016-05-05 13:00:58,445 INFO  [pool-3-thread-1] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:252) - So far, 40 out of 45 questions have been retained
2016-05-05 13:00:58,446 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 5812
2016-05-05 13:00:59,466 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 13411
2016-05-05 13:01:00,381 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 5830
2016-05-05 13:01:01,600 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 5735
2016-05-05 13:01:02,812 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 6293
2016-05-05 13:01:03,792 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 6246
2016-05-05 13:01:04,757 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 6308
2016-05-05 13:01:05,702 INFO  [pool-3-thread-1] api.PipelineQuestionAnswerer$3 (PipelineQuestionAnswerer.java:150) - 7721
2016-05-05 13:01:06,632 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:160) - Attempting to create ranker.
2016-05-05 13:01:15,051 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:163) - Writing training data to disk
2016-05-05 13:01:15,095 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:167) - Writing training data to disk done
2016-05-05 13:01:15,105 ERROR [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:194) - The key [ranker_id] was not in the map
2016-05-05 13:01:15,105 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:196) - Ranker ID: null
2016-05-05 13:01:15,195 INFO  [main] pipeline.PipelineDriver (PipelineDriver.java:133) - PipelineDriver total elapsed time: 1 minute 29 seconds
```

**Comment by stevenoh93** [comment] 2016-05-05 11:56
Hi,
During indexing, the corpus might have more than 50 questions, but what the service is looking for is 50 "good" questions, which means questions that have a selected "correct" answer.
There may be questions in the corpus that have not been answered yet, and the `PipelineQuestionAnswerer` will remove them to save space since they will be removed during the training phase anyway.

```
2016-05-05 13:00:58,445 INFO  [pool-3-thread-1] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:252) - So far, 40 out of 45 questions have been retained
```

this line means 5 questions did not have any candidate answers, so they were removed.
Usually, corpus with around 50K questions seemed to yield good results for us.

**Comment by poonamsaini17** [comment] 2016-05-06 12:12
I am not understanding .. Can you please tell in  more detail ?
2016-05-06 17:36:44,291 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:160) - Attempting to create ranker.
2016-05-06 17:37:09,237 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:163) - Writing training data to disk
2016-05-06 17:37:09,255 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:167) - Writing training data to disk done
2016-05-06 17:37:09,291 ERROR [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:194) - The key [ranker_id] was not in the map
2016-05-06 17:37:09,291 INFO  [main] pipeline.RnrMergerAndRanker (RnrMergerAndRanker.java:196) - Ranker ID: null
2016-05-06 17:37:09,361 INFO  [main] pipeline.PipelineDriver (PipelineDriver.java:133) - PipelineDriver total elapsed time: 2 minutes 58 seconds

Attaching a new output file
[Uploading outputOfPipelineRunner.txt…]()

**Comment by poonamsaini17** [comment] 2016-05-06 12:13
closed by mistake

**Comment by stevenoh93** [comment] 2016-05-06 19:04
Sorry if that wasn't clear.

The StackExchange database has a system where the user asking the question chooses a 'correct' answer among the various answers he/she gets.

The ranker needs at least 50 questions to train. However, it ignores any questions that do not have a selected answer, because they have no value in the training process.

Therefore, to save space, the `PipelineQuestionAnswerer` discards such questions from the training data before they are sent off to the training process.

In the output log, you'll find this message:

```
So far, 40 out of 45 questions have been retained
```

This means, that out of 45 questions you had, five of them did not have a chosen answer and was discarded.
So even if you have more than 50 questions to feed into the training process, some of them might be discarded, and you may end up with less than 50 questions at the end. That would result in failure to create the ranker.

Essentially, I believe your data set is still too small for this training process.

**Comment by dgterry** [comment] 2016-05-06 19:14
Thanks @stevenoh93 
@poonamsaini17 assuming it fits your needs, one thing that might make things easier on you is when going to the [stack exchange archive site](https://archive.org/details/stackexchange?cm_mc_uid=53113079501414612427118&cm_mc_sid_50200000=1462561883)
is to use the english.stackexchange.com.7z file.  This is the file we used to host the running version of the app and we can confirm it is large enough to pass the training phase.

**Comment by poonamsaini17** [comment] 2016-05-07 02:42
@stevenoh93 
Thanks for clearing the out ..
But yesterday i tried with huge data 
170 out 180  have been retained ..
Now the count is more than 50 ..

Still Ranker id happened to be null..

**Comment by poonamsaini17** [comment] 2016-05-09 05:12
[outputOfPipelineRunner.txt](https://github.com/watson-developer-cloud/professor-languo/files/254329/outputOfPipelineRunner.txt)

**Comment by stevenoh93** [comment] 2016-05-09 13:46
Could you attach the res/trainingdata.csv?

**Comment by stevenoh93** [comment] 2016-05-09 14:04
Could you also tell us what corpus you are using?

**Comment by poonamsaini17** [comment] 2016-05-09 16:54
English one was taking hell lot of time ..
So i tried with biology..

**Comment by stevenoh93** [comment] 2016-05-09 17:22
Do you have the res/trainingdata.csv file? I think that could clear up some problems that you might be having. It's not yet clear to me what the problem is just from the log statements.

**Comment by poonamsaini17** [comment] 2016-05-10 14:29
![image](https://cloud.githubusercontent.com/assets/15319704/15150160/b891201c-16e9-11e6-900d-fc85ed39e98c.png)

**Comment by poonamsaini17** [comment] 2016-05-10 14:31
I  am not allowed to upload csv file here  , so i just pasted the screen shot of that file..

**Comment by stevenoh93** [comment] 2016-05-10 16:01
Maybe check it in to a repository and share the link? The screenshot is not enough information unfortunately :(

**Comment by stevenoh93** [comment] 2016-05-10 18:44
Okay I **think** I know what the problem is.
Here is a requirement from the [documentation](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/retrieve-rank/training_data.shtml)

> The number of records must be at least 50 times the number of fields that are identified in your Solr configuration. For example, if your collection defines five fields, you must have at least 250 records in your training data. 

With the addition of custom scorers, this requirement is not met.
Could you disable all custom scorers by going to `src/main/resources/app_config.properties` and delete all scorers? The field name is `EGA_METADATA_FEATURE_SCORERS`, and you want it to look like this:

```
EGA_METADATA_FEATURE_SCORERS=
```

After saving, try running it again.

**Comment by germanattanasio** [comment] 2016-08-21 01:32
I'm going to close this. I think @stevenoh93's suggestion fixed the issue

**Closed as completed by germanattanasio** 2016-08-21 01:32 UTC
